### ISSUE TITLE
Add Gradient Background and remove background image

### ISSUE THREAD

**Issue by 97k** [aditya98ak/spam-ham-web-app#3]
Remove the gradient image and add a gradient using CSS!
[Check out this link for css-matic gradients](https://www.cssmatic.com/gradient-generator#'\-moz\-linear\-gradient\%28left\%2C\%20rgba\%28248\%2C80\%2C50\%2C1\%29\%200\%25\%2C\%20rgba\%28241\%2C111\%2C92\%2C1\%29\%2050\%25\%2C\%20rgba\%28246\%2C41\%2C12\%2C1\%29\%2051\%25\%2C\%20rgba\%28240\%2C47\%2C23\%2C1\%29\%2071\%25\%2C\%20rgba\%28231\%2C56\%2C39\%2C1\%29\%20100\%25\%29\%3B')

**Comment by maliMirkec** [comment]
I'll do it!

**Comment by 97k** [comment]
Do ask me anything, if you get stuck anywhere :smiley:

**Comment by maliMirkec** [comment]
Done #4.

**Comment by Zunaid24** [comment]
Is this still available?

**Comment by 97k** [comment]
@Zunaid24 This has been merged!
Btw, I'll be opening new issues soon.
Consider staring the repo, so that coming here back would be handy for you!

Cheers!
